package com.agent.editor.agent.v2.event;

public enum EventType {
    TASK_STARTED,
    TASK_COMPLETED,
    TASK_FAILED,
    PLAN_CREATED,
    WORKER_SELECTED,
    WORKER_COMPLETED,
    SUPERVISOR_COMPLETED,
    ITERATION_STARTED,
    DECISION_MADE,
    TEXT_STREAM_STARTED,
    TEXT_STREAM_DELTA,
    TEXT_STREAM_COMPLETED,
    TOOL_CALLED,
    TOOL_SUCCEEDED,
    TOOL_FAILED,
}
